---
- name: Update apt-get repositories
  tags: [online]
  apt: update_cache=yes

- name: Install General Requirements
  tags: [online]
  apt: pkg={{ item }} state=present
  with_items:
    - ack-grep
    - vim
    - git
    - tree
    - curl
    - wget
